### PR TITLE
Add ability to use cowsay's options

### PR DESCRIPTION
**Pull request by azakordonets**
You can pass cow's option in a more or less verbose way . Both should work : 
```
{
	"text" : "I'm a moooodule",
        "token": "your_token",
	"e" : "oO",
	"T" : "U "
}
```

```
{
	"text" : "I'm a moooodule",
        "token": "your_token",
	"eyes" : "oO",
	"tongue" : "U "
}
```

### CODE REVIEW

**Comment by azakordonets** [comment]
Added unit tests and also improved code a bit to make error handling more user friendly

**Comment by mikefrancis** [comment]
Hi there!

Wow, this is awesome, I see you've tackled both issues!

However these issues were really meant for beginners and I think it's pretty apparent you're above that level.

I'm going to close this PR but others can feel free to use this.

Thanks though :smile:

**Comment by azakordonets** [comment]
No problem. Actually, i just started to learn javascript and this is the first Javascript project i have ever worked :) This is why i signed up for it - i wanna learn javascript and node.js to use it in my future projects. So, in this matter, i'm a total beginner :)

**Comment by mikefrancis** [comment]
@azakordonets Ah ok. Well thanks anyway, it seems like you're definitely on the right track with your JS learning!

Ideally looking for someone who is new to GitHub too, looking to make some contributions to Open Source.

If no-one ends up looking at this I will gladly merge your code somewhere down the line.

Thanks again.

**Comment by mikefrancis** [comment]
Ok, let's merge in your options code! Can you please pull down the latest changes?

**Comment by azakordonets** [comment]
Can you help me to figure out how to do that properly ? Will just `git pull --rebase` work, or do i need to specify your remote ?

**Comment by mikefrancis** [comment]
Hmm, ideally you should have created a new branch for this and it would have been a lot easier. Never work on the master branch!

If you do a `git pull` you will get notified of any merge conflicts, fix those (in a new branch) and then push that branch up in a new PR.

If you need any more help let me know!

**Comment by mikefrancis** [comment]
You could just copy your changes somewhere from `src/index.js` and start from scratch as it's only the `src/index.js` file that's needed.

**Pull request closed without merging**
